# Generated by Django 5.2.11 on 2026-02-26 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-camera', help_text='Bootstrap icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily hire rate in KES', max_digits=10)),
                ('replacement_value', models.DecimalField(decimal_places=2, help_text='Value for damage assessment', max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('hired', 'Hired Out'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='available', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (used if no uploaded image)', max_length=500)),
                ('condition_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.category')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['category', 'name'],
            },
        ),
    ]
